### PR TITLE
fix for issue #15

### PR DESCRIPTION
**Pull request by 17h13**
These two commits, add a test to verify that the parameter to the fetch function is used and also fix issue #15 

Thanks
Ithier

### CODE REVIEW

**Comment by lukekarrys** [comment]
+1 on the feature.

@17h13 Can you resync this with the latest master and leave the version in `package.json` untouched? We normally do the version bump as part of a separate commit.

**Comment by kamilogorek** [comment]
+1

**Comment by HenrikJoreteg** [comment]
Makes sense to me +1. @17h13 we typically handle the version bump as part of the release process and not in the PR. Perhaps just re-sync with master and undo the version bump.

**Comment by lukekarrys** [comment]
Published as `4.1.0`

**Comment by 17h13** [comment]
Apologies for the delayed response. 
Thank you for commited my pull request and I will be careful next time not to touch the version in package.json !

**Pull request merged**
