### PR TITLE
Return fetches, and add tests

### PR DESCRIPTION
**Pull request by dazld**
At the moment, if your fetch returns something (like a promise) then the two methods `getOrFetch` and `fetchById` do not let you do anything with what is returned from the fetch method. 

I've added some return statements and tests to cover this.

### CODE REVIEW

**Comment by lukekarrys** [comment]
Thanks for the pr!

+1 from me. I'll get another core team member to look it over as well and then we can merge this.

**Comment by lukekarrys** [comment]
Ping @AmpersandJS/core-team

**Comment by wraithgar** [comment]
Good fix that moves us in the right direction. I'm gonna +0 because I would like someone who knows more about promises weigh in on adding bluebird to the test suite, or if we can get away with somehow testing this change w/o it.

**Comment by HenrikJoreteg** [comment]
I think it's fine that the tests include bluebird as part of a sync mixin, given that's what it's trying to test.

@lukekarrys, I'd say ship this puppy.

**Comment by dazld** [comment]
Just realised I didn't actually call the methods which I changed in the mixin - just `fetch` itself. I'll update it.

**Comment by dazld** [comment]
Done - It does not cover the case where a model is already existing in the collection - ie, the interface is not consistent for fetching / returning an existing model, sadly. That's a potential footgun. 

However, I suppose if a developer wants to use promises as a fetch, then this method would have to be wrapped somehow - but let's not go down that road just here, and I think it's possibly a little out of scope for the PR. What do you think?

Thanks for the quick feedback!

**Comment by lukekarrys** [comment]
I'm happy shipping this as is. Thanks for the great work @dazld.

@HenrikJoreteg @wraithgar Any thoughts on the semver level of this?

**Comment by lukekarrys** [comment]
Looks like I created a conflict with the last PR I merged. I'll clean it up.

**Comment by latentflip** [comment]
Given that it was only returning the result of the callback, and only on one branch of the code, before - I'd say this is a minor.

**Comment by lukekarrys** [comment]
Published as `4.1.0`

**Pull request merged**
