### PR TITLE
update sync and use xhrImplementation to mock success tests

### LINKED ISSUE #9: Undo hack job to override xhr in tests
https://github.com/AmpersandJS/ampersand-sync/pull/18 will also [this brittle hack](https://github.com/AmpersandJS/ampersand-collection-rest-mixin/blob/master/test/lib/success-sync.js) to be undone.

### PR DESCRIPTION
**Pull request by lukekarrys**
Closes #9

### CODE REVIEW

**Comment by lukekarrys** [comment]
Since `ampersand-sync` has some outstanding issues that will require a major version bump, I think we should hold off on merging this until we have completed those, since any major sync version bump will also require a major version bump here. I put them all into a `v4` milestone over on that repo so that they can be tracked over there.

**Comment by gonsfx** [comment]
Any progress on this?

Anyway - whats the harm in releasing more major versions?
Shouldn't be a problem with NPM and Semver.

**Comment by wraithgar** [comment]
:shipit:

**Comment by lukekarrys** [comment]
The one failing test on the push is due to travis trying to use ruby instead of node. The PR build passes. Mergning.

**Comment by lukekarrys** [comment]
Published as `v4.0.0`

**Comment by constantx** [comment]
:+1:

**Pull request merged**
